export const BLE_START_SCAN = 'START_SCAN'
export const BLE_STOP_SCAN = 'STOP_SCAN'
export const BLE_UPDATE_DEVICES = 'UPDATE_DEVICES'
export const BLE_CLEAR_DEVICES = 'CLEAR_DEVICES'
export const BLE_UPDATE_STATE = 'UPDATE_STATE'
export const BLE_UPDATE_SCANNING = 'UPDATE_SCANNING'

export const LOG_ADD_ENTRY = 'LOG_ADD_ENTRY'
