// BLE
export const BLE_INIT = 'BLE_INIT'
export const BLE_SET_SCANNING = 'BLE_SET_SCANNING'
export const BLE_SET_CONNECTED = 'BLE_SET_CONNECTED'
export const BLE_FOUND_DEVICE = 'BLE_FOUND_DEVICE'
export const BLE_START_SCAN = 'START_SCAN'
export const BLE_STOP_SCAN = 'STOP_SCAN'
export const BLE_UPDATE_DEVICES = 'UPDATE_DEVICES'
export const BLE_UPDATE_STATE = 'UPDATE_STATE'
export const BLE_UPDATE_SCANNING = 'UPDATE_SCANNING'
export const BLE_SEND_DATA = 'BLE_SEND_DATA'

export const LOG_ADD_ENTRY = 'LOG_ADD_ENTRY'

// UI
export const SHOW_SNACK = 'SHOW_SNACK'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const HIDE_SNACK = 'HIDE_SNACK'
